/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xA4, 0xC1, 0x75, 0x31, 0x9D, 0x52, 0x6B, 0xE8}

// Esc Key
#define VIAL_UNLOCK_COMBO_ROWS { 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define CORE75_DISABLE_CUSTOM_DIRECT_RGB
#define VIALRGB_NO_DIRECT

#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
#define VIAL_ALT_REPEAT_KEY_ENTRIES 4

#define CAPS_LOCK_LED_INDEX 44
